### ISSUE TITLE
Does this tool support multiple (Procedure, Expected Result) pairs for the same test case?

### ISSUE THREAD

**Issue by daiq** [mozilla/jira2moztrap#1]
As titled. Thanks.

**Comment by camd** [comment]
MozTrap supports multiple `steps` or what you might call `procedures` per test case.  basically pairs of actions and expected pairs.  When converting from the Jira `CSV` files into MozTrap, we only have one line per test.  So we only get one action and one expected entry per Jira test case.  I hope that makes sense.  This was just a simple little set of scripts we've used at Mozilla to convert cases from Jira.  So it wasn't meant to be very robust and feature rich.
